In [1]:
import numpy as np
np.array((np.linspace(20, stop = 1)))

array([20.        , 19.6122449 , 19.2244898 , 18.83673469, 18.44897959,
       18.06122449, 17.67346939, 17.28571429, 16.89795918, 16.51020408,
       16.12244898, 15.73469388, 15.34693878, 14.95918367, 14.57142857,
       14.18367347, 13.79591837, 13.40816327, 13.02040816, 12.63265306,
       12.24489796, 11.85714286, 11.46938776, 11.08163265, 10.69387755,
       10.30612245,  9.91836735,  9.53061224,  9.14285714,  8.75510204,
        8.36734694,  7.97959184,  7.59183673,  7.20408163,  6.81632653,
        6.42857143,  6.04081633,  5.65306122,  5.26530612,  4.87755102,
        4.48979592,  4.10204082,  3.71428571,  3.32653061,  2.93877551,
        2.55102041,  2.16326531,  1.7755102 ,  1.3877551 ,  1.        ])

In [2]:
l1 = [1, 3, 5, 7]
l1.append(9)
l1

[1, 3, 5, 7, 9]

In [3]:
from itertools import permutations, combinations
perm5 = combinations(['Name', 'Mobile', 'Email', 'Address', 'City'], 5)
print(list(perm5))

[('Name', 'Mobile', 'Email', 'Address', 'City')]


In [4]:
perm4 = combinations(['Name', 'Mobile', 'Email', 'Address', 'City'], 4)
print(list(perm4))

[('Name', 'Mobile', 'Email', 'Address'), ('Name', 'Mobile', 'Email', 'City'), ('Name', 'Mobile', 'Address', 'City'), ('Name', 'Email', 'Address', 'City'), ('Mobile', 'Email', 'Address', 'City')]


In [5]:
import numpy as np
import pandas as pd
combination_3 = combinations(['Name', 'Mobile', 'Email', 'Address', 'City'], 3)
lst = list(combination_3)
l = np.array(lst)
df3 = pd.DataFrame(l, columns = ['Attr1', 'Attr2', 'Attr3'])
df3

Attr1    Attr2    Attr3
0    Name   Mobile    Email
1    Name   Mobile  Address
2    Name   Mobile     City
3    Name    Email  Address
4    Name    Email     City
5    Name  Address     City
6  Mobile    Email  Address
7  Mobile    Email     City
8  Mobile  Address     City
9   Email  Address     City

In [6]:
combination_4 = combinations(['Name', 'Mobile', 'Email', 'Address', 'City'], 4)
lst = list(combination_4)
l = np.array(lst)
df2 = pd.DataFrame(l, columns = ['Attr1', 'Attr2', 'Attr3', 'Attr4'])
df2

Attr1   Attr2    Attr3    Attr4
0    Name  Mobile    Email  Address
1    Name  Mobile    Email     City
2    Name  Mobile  Address     City
3    Name   Email  Address     City
4  Mobile   Email  Address     City

In [7]:
combination_5 = combinations(['Name', 'Mobile', 'Email', 'Address', 'City'], 5)
lst = list(combination_5)
l = np.array(lst)
df = pd.DataFrame(l, columns = ['Attr1', 'Attr2', 'Attr3', 'Attr4', 'Attr5'])
df

Attr1   Attr2  Attr3    Attr4 Attr5
0  Name  Mobile  Email  Address  City

In [8]:
data = pd.concat([df, df2, df3], sort = True)
data.reset_index(drop = True, inplace = True)
data.fillna(0, inplace = True)
data

Attr1    Attr2    Attr3    Attr4 Attr5
0     Name   Mobile    Email  Address  City
1     Name   Mobile    Email  Address     0
2     Name   Mobile    Email     City     0
3     Name   Mobile  Address     City     0
4     Name    Email  Address     City     0
5   Mobile    Email  Address     City     0
6     Name   Mobile    Email        0     0
7     Name   Mobile  Address        0     0
8     Name   Mobile     City        0     0
9     Name    Email  Address        0     0
10    Name    Email     City        0     0
11    Name  Address     City        0     0
12  Mobile    Email  Address        0     0
13  Mobile    Email     City        0     0
14  Mobile  Address     City        0     0
15   Email  Address     City        0     0

In [9]:
i=6
i<5

False

In [10]:
L=[1,3,2]
sorted(L)

[1, 2, 3]

In [11]:
def Print(A):
    for a in A:
        print(a+'1')
        
Print(['a','b','c'])

a1
b1
c1


In [12]:
with open("Example3.txt","w") as file1:
    file1.write("This is line C\n")

In [13]:
import numpy as np
a=np.array([1,1,1,1,1])
a+10 

array([11, 11, 11, 11, 11])

In [14]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]]) 
Z=np.dot(X,Y)
Z

array([[2, 1],
       [1, 2]])

In [15]:
!pip install nba_api

In [18]:
data.to_csv(r'C:\Code\myfile.csv', index = False)