# <font color = 'green'>Numpy</font>
## Source:
 - Book: [Johansson | (p 64 / 709)]
 - Book: [Nelli | (p 69 / 576)]
 - Book: [McKinney | (p 98 / 529)]
 
## Topics:
 - [Part I: Numpy Basics](#Part-I:-Numpy-Basics)
 - [Part II: Creating Numpy Arrays](#Part-II:-Creating-Numpy-Arrays)
 - [Part III: Array Indexing and Slicing](#Part-III:-Array-Indexing-and-Slicing)
 - [Part IV: Array Reshaping and Resizing](#Part-IV:-Array-Reshaping-and-Resizing)
 - [Part V: Vectorization and Array Broadcasting](#Part-V:-Vectorization-and-Array-Broadcasting)
 - [Part VI: Input and Output](#Part-VI:-Input-and-Output)

# <font color = 'green'>Part I: Numpy Basics</font>

### <font color = 'green'>1.1 Introduction</font>

NumPy’s main object is the homogeneous multidimensional array. It is a grid (table) of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes.

For example, the coordinates of a point in 3D space <code>[1, 2, 1]</code> has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

<code>[[ 1., 0., 0.],
  [ 0., 1., 2.]]
</code>
 
NumPy’s array class is called <code>ndarray</code>. It is also known by the alias <code>array</code>. Note that <code>numpy.array</code> is not the same as the Standard Python Library class <code>array.array</code>, which only handles one-dimensional arrays and offers less functionality.

### <font color = 'green'>1.2 Difference between list and arrays:</font>

 - An important difference is that while Python lists are generic containers of objects, NumPy arrays are homogenous and typed arrays of fixed size. 
  - <b>Homogenous</b>: means that all elements in the array have the same data type. 
  - <b>Fixed size</b>: means that an array cannot be resized (without creating a new array). 

 - For these and other reasons, operations and functions acting on NumPy arrays can be much more efficient than those using Python lists.
 - In addition to the data structures for arrays, NumPy also provides a large collection of basic operators and functions that act on these data structures, as well as submodules with higher-level algorithms such as linear algebra and fast Fourier transform.
 
### <font color = 'green'>1.3 The NumPy Array object:</font> 

<p>The core of the NumPy library is the data structures for representing multidimensional arrays of homogeneous data. Homogeneous refers to all elements in an array having the same data type.</p> 

<p>The main data structure for multidimensional arrays in NumPy is the <code>ndarray</code> class. In addition to the data stored in the array, this data structure also contains important metadata about the array, such as its shape, size, data type, and other attributes. See the following Table for a more detailed description of these attributes. 
    A full list of attributes with descriptions is available in the ndarray docstring, which can be accessed by calling <code>help(np.ndarray)</code> in the Python interpreter or <code>np.ndarray?</code> in an IPython console.</p>
    
###  <font color = 'green'>Basic <code>attributes</code> of the <code>ndarray</code> class:</font>

<img src="assets/1_ndarray_attributes.jpg" width=800px />

The more important attributes of an ndarray object are:

 - <code>ndarray.ndim</code>: the number of axes (dimensions) of the array.
 - <code>ndarray.shape</code>: the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.
 - <code>ndarray.size</code>: the total number of elements of the array. This is equal to the product of the elements of shape.
 - <code>ndarray.dtype</code>: an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
 - <code>ndarray.itemsize</code>: the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
 - <code>ndarray.data</code>: the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

####  <font color = 'green'>Example: <code>ndarray</code> Attributes:</font>

In [1]:
import numpy as np
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [2]:
a.ndim

2

In [3]:
a.shape

(4, 4)

In [4]:
a.size

16

In [5]:
a.dtype.name

'int32'

In [6]:
a.itemsize

4

In [7]:
import numpy as np
A = np.random.randint(1, 30, 27)
A = A.reshape(3, 3, 3)
print(A)
print(f'A - Shape    : {A.shape}')
print(f'A - Size     : {A.size}')
print(f'A - Dimention: {A.ndim}')
print(f'A - Datatype : {A.dtype.name}')
print(f'A - Item Size: {A.itemsize}')

[[[ 2 19  5]
  [13 29 27]
  [ 3  2 26]]

 [[23 24  9]
  [22 20  2]
  [ 4 21 23]]

 [[ 7 27 15]
  [26 14 26]
  [22 19  6]]]
A - Shape    : (3, 3, 3)
A - Size     : 27
A - Dimention: 3
A - Datatype : int32
A - Item Size: 4


### <font color = 'green'>1.4 The NumPy Array datatype:</font> 
In the previous section, we encountered the dtype attribute of the <code>ndarray</code> object. This attribute describes the data type of each element in the array (remember, since NumPy arrays are homogeneous, all elements have the same data type). The basic numerical data types supported in NumPy are shown in Table 2-2. Nonnumerical data types, such as strings, objects, and user-defined compound types, are also supported.

<img src="assets/2_ndarray_dtype.jpg" width=800px />

For numerical work the most important data types are int (for integers), float (for floating-point numbers), and complex (for complex floating-point numbers). Each of these data types comes in different sizes, such as int32 for 32-bit integers, int64 for 64-bit integers, etc. This offers more fine-grained control over data types than the standard Python types, which only provides one type for integers and one type for floats.

For numerical work the most important data types are int (for integers), float (for floating-point numbers), and complex (for complex floating-point numbers). Each of these data types comes in different sizes, such as int32 for 32-bit integers, int64 for 64-bit integers, etc. This offers more fine-grained control over data types than the standard Python types, which only provides one type for integers and one type for floats.

It is usually not necessary to explicitly choose the bit size of the data type to work with, but it is often necessary to explicitly choose whether to use arrays of integers, floatingpoint numbers, or complex values.

The following example demonstrates how to use the dtype attribute to generate arrays of <code>integer-</code>, <code>float-</code>, and <code>complex</code>-valued elements:

In [8]:
a = np.array([1,2,3], dtype=np.int)
a

array([1, 2, 3])

In [9]:
b = np.array([1,2,3], dtype=np.float)
b

array([1., 2., 3.])

In [10]:
c = np.array([1,2,3], dtype=np.complex)
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [11]:
b == c

array([ True,  True,  True])

In [12]:
# use the array_equal() method to check equality of array objects.
b = np.array([1,2,3], dtype=np.float)
c = np.array([1,2,3], dtype=np.complex)
value = np.array_equal(b, c)
value

True

### <font color = 'green'>1.6 The NumPy Array Equality:</font> 

#### <code>numpy.array_equal(a, b)</code>

True if two arrays have the same shape and elements, False otherwise.
 - <b>Parameters</b>: a, b: array_like (list, tuple, ndarray)
 - <b>Output</b>: Returns True if arrays are equal, false otherwise.

In [13]:
import numpy as np
a = np.arange(1, 10).reshape(3,3)
b = np.array(a, dtype = np.complex)
np.array_equal(a, b)

True

In [14]:
m = [1,3,5]
n = [1.0 + 0.j,3.0 + 0.j, 5.0 + 0.j]
m == n

True

###  <font color = 'green'>1.5 Changing <code>ndarray</code> Datatype:</font>

Once a NumPy array is created, its dtype cannot be changed, other than by creating a new copy with type-casted array values. Typecasting an array is straightforward and can be done in 2 ways:
1. using the <code>np.array</code> function
2. using the <code>astype()</code> method of the <code>ndarray</code> class

In [15]:
data = np.array([1, 2, 3], dtype=np.float)
print(data.dtype)
print(data)

float64
[1. 2. 3.]


### Changing datatype typecasting with the <code>np.array()</code> method:

In [16]:
data = np.array(data, dtype=np.int)
print(data.dtype)
print(data)

int32
[1 2 3]


In [17]:
data = np.array([1, 2, 3], dtype=np.int)
print(data.dtype)
data

int32


array([1, 2, 3])

### Changing datatype typecasting using the <code>astype()</code> method of the <code>ndarray</code> class:

In [18]:
data.astype(np.float)

array([1., 2., 3.])

### Create Arrays with fixed datatypes:
In some cases, depending on the application and its requirements, it is essential to create arrays with data type appropriately set to, for example, int or complex. The default type is <code>float</code>. Consider the following example:

In [19]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

### <font color = 'green'>1.7 Important NumPy Array <code>methods</code>:</font> 

#### Method 1: <code>array.reshape()</code>:

In [20]:
a = np.random.randint(0, 100, 9)
a.reshape(3, 3)

array([[36, 82, 91],
       [46, 79, 20],
       [80, 76, 40]])

#### Method 2: <code>array.min()</code>, <code>array.max()</code>, <code>array.argmin()</code>, <code>array.argmax()</code>:

In [21]:
import numpy as np
b = np.random.randint(0, 100, 9)
b

array([98, 38, 53, 78, 97, 87, 88, 72,  9])

In [22]:
print(f'Min: {b.min()}; min_index: {b.argmin()}')
print(f'Max: {b.max()}; max_index: {b.argmax()}')

Min: 9; min_index: 8
Max: 98; max_index: 0


# <font color = 'green'>Part II: Creating Numpy Arrays</font>

Arrays can be generated in a number of ways, depending on their properties and the applications they are used for. For example, as we saw in the previous section, one way to initialize an ndarray instance is to use the np.array function on a Python list, which, for example, can be explicitly defined. However, this method is obviously limited to small arrays. In many situations it is necessary to generate arrays with elements that follow some given rule, such as filled with constant values, increasing integers, uniformly spaced numbers, random numbers, etc. In other cases we might need to create arrays from data stored in a file. The requirements are many and varied, and the NumPy library provides a comprehensive set of functions for generating arrays of various types.

<img src="assets/3_generating_arrays.jpg" width=600px />

### <font color = 'blue'>2.1 Method 1: Passing arguments to the <code>np.array()</code> function</font>

Using the np.array function, NumPy arrays can be constructed from explicit Python lists, iterable expressions, and other array-like objects (such as other ndarray instances). For example, to create a one-dimensional array from a Python list, we simply pass the Python list as an argument to the np.array function:

In [23]:
import numpy as np
l1 = [x for x in range(1,7)]
a = np.array(l1) # Creating array.
print(a)

[1 2 3 4 5 6]


#### The <code>array()</code> function:

The <code>array()</code> function, in addition to lists, can accept tuples and sequences of tuples.

In [24]:
import numpy as np
def array_gen(m, n):
    """A program for creating m X n list of lists."""
    result = []
    for c in range(m):
        j = [k for k in range((c*n + 1), (c*n + 1 + n))]
        result.append(j)
    matrix  = np.array(result)
    print(matrix)

array_gen(4, 4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [25]:
# achieve the same as array_gen with a single function call:
m = np.arange(1,17).reshape(4, 4)
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### <font color = 'blue'>2.2 Method 2: Arrays Filled with Constant Values</font>

The functions np.zeros and np.ones create and return arrays filled with <code>zeros</code> and <code>ones</code>, respectively. They take, as first argument, an integer or a tuple that describes the number of elements along each dimension of the array. 

Like other array-generating functions, the np.zeros and np.ones functions also accept an optional keyword argument that specifies the data type for the elements in the array. By default, the data type is float64, and it can be changed to the required type by explicitly specifying the dtype argument.

For example, to create a 2 × 3 array filled with zeros, and an array of length 4 filled with ones, we can use:

In [26]:
# np.zeros() and np.ones()
import numpy as np
a = np.zeros(3, dtype = np.int)
b = np.ones(3, dtype = np.complex)
print(a)
print(b)

[0 0 0]
[1.+0.j 1.+0.j 1.+0.j]


 - <code>np.full()</code>: An array filled with an arbitrary constant value can be generated by first creating an array filled with ones and then multiplying the array with the desired fill value. However, NumPy also provides the function <code>np.full</code> that does exactly this in one step. The following two ways of constructing arrays with ten elements, which are initialized to the numerical value 5.4 in this example, produces the same results, but using np.full is slightly more efficient since it avoids the multiplication.

In [27]:
# np.full()
m1 = 3.14 * np.ones(3)
m2 = np.full(3, 3.14)
print("m1: ", m1)
print("m2: ", m2)

m1:  [3.14 3.14 3.14]
m2:  [3.14 3.14 3.14]


- <code>np.fill()</code>: An already created array can also be filled with constant values using the <code>np.fill</code> function, which takes an array and a value as arguments, and set all elements in the array to the given value. The following two methods to create an array therefore give the same results:

In [28]:
# np.fill()

# In this last example, we also used the np.empty() function, which generates an array with uninitialized values, of the given size. This function should only be used when the initialization of all elements can be guaranteed by other means, such as an explicit loop over the array elements or another explicit assignment.

import numpy as np
a = np.empty(4)
a.fill(3)
a.reshape(2,2)

array([[3., 3.],
       [3., 3.]])

### <font color = 'blue'>2.3 Method 3: Arrays Filled with Linear Incremental Sequences: <code>arange()</code> and <code>linspace()</code></font>

In numerical computing it is very common to require arrays with evenly spaced values between a starting value and ending value. NumPy provides two similar functions to create such arrays: <code>np.arange</code> and <code>np.linspace</code>. Both functions take three arguments, where the first two arguments are the start and end values. The third argument of np.arange is the increment, while for np.linspace it is the total number of points in the array.

For example, to generate arrays with values between 1 and 10, with increment 1, we could use either of the following:

In [29]:
a = np.arange(1, 11, 1)
b = np.linspace(1, 10, 10) # Specify the start, stop and number values needed between them. Please note the stop value is also considered in this case
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


However, note that <code>np.arange</code> does not include the end value (10), while by default <code>np.linspace</code> does (although this behavior can be changed using the optional endpoint keyword argument). Whether to use <code>np.arange</code> or <code>np.linspace</code> is mostly a matter of personal preference, but it is generally recommended to use np.linspace whenever the increment is a noninteger.

### <font color = 'blue'>2.4 Method 4: Arrays Filled with Logarithmic Incremental Sequences: <code>logspace()</code></font>

The function <code>np.logspace</code> is similar to <code>np.linspace</code>, but the increments between the elements in the array are logarithmically distributed, and the first two arguments, for the start and end values, are the powers of the optional base keyword argument (which defaults to 10). For example, to generate an array with logarithmically distributed values between 1 and 100, we can use:

In [30]:
np.logspace(0, 2, 8) # 5 data points between 10**0=1 to 10**2=100

array([  1.        ,   1.93069773,   3.72759372,   7.19685673,
        13.89495494,  26.82695795,  51.79474679, 100.        ])

### <font color = 'blue'>2.5 Method 5: Creating Uninitialized Arrays: <code>np.empty()</code></font>

To create an array of specific size and data type, but without initializing the elements in the array to any particular values, we can use the function <code>np.empty</code>. The advantage of using this function, for example, instead of <code>np.zeros</code>, which creates an array initialized with zero-valued elements, is that we can avoid the initiation step. If all elements are guaranteed to be initialized later in the code, this can save a little bit of time, especially when working with large arrays. To illustrate the use of the <code>np.empty</code> function, consider the following example:

In [31]:
np.empty(5, dtype=np.float)

array([ 2.02566915e-322,  1.47966021e-316,  4.72986829e-318,
       -4.22974022e-242,  1.47966337e-316])

Here we generated a new array with three elements of type <code>float</code>. There is no guarantee that the elements have any particular values, and the actual values will vary from time to time. For this reason it is important that all values are explicitly assigned before the array is used; otherwise unpredictable errors are likely to arise. Often the <code>np.zeros</code> function is a safer alternative to <code>np.empty</code>, and if the performance gain is not essential, it is better to use <code>np.zeros</code>, to minimize the likelihood of subtle and hard-toreproduce bugs due to uninitialized values in the array returned by <code>np.empty</code>.

### <font color = 'blue'>2.6 Method 6: Creating Matrix Arrays: <code>np.identity()</code>, <code>np.eye()</code>, and <code>np.diag()</code></font>:

 - <b><code>np.identity()</code></b>:

Matrices, or two-dimensional arrays, are an important case for numerical computing. NumPy provides functions for generating commonly used matrices. In particular, the function <code>np.identity</code> generates a square matrix with ones on the diagonal and zeros elsewhere:

In [32]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- <b><code>np.eye()</code></b>:

The similar function <code>numpy.eye</code> generates matrices with ones on a diagonal (optionally offset). This is illustrated in the following example, which produces matrices with nonzero diagonals above and below the diagonal, respectively:

In [33]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.eye(4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [35]:
np.eye(4, k = -1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

 - <b><code>np.diag()</code></b>:

To construct a matrix with an arbitrary one-dimensional array on the diagonal, we can use the <code>np.diag</code> function (which also takes the optional keyword argument k to specify an offset from the diagonal), as demonstrated here:

In [36]:
a = np.arange(1,5,1)
b = np.diag(a)
b

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### <font color = 'blue'>2.7 Method 7: Numpy Random Sampling:</font>

Numpy has a lot of options to create random numbered arrays through random sampling in the <code>numpy.random</code> module.

<img src="assets/4_numpy_random.jpg" width=850px />

Source: [Numpy 1.16 Documentation | Routines](https://numpy.org/doc/1.16/reference/routines.random.html)


### Function 1: <font color = 'blue'><code>numpy.random.rand()</code></font>

<code>numpy.random.rand(d0, d1, ..., dn)</code>

 - Random values in a given shape.

 - Create an array of the given shape and populate it with random samples from a _<b>uniform distribution</b>_ over [0, 1).

 - <b>Parameters:</b>	
        d0, d1, …, dn : int, optional
        The dimensions of the returned array, should all be positive. If no argument is given,  then a single Python float is returned.

 - <b>Returns:</b>	
        out : ndarray, shape (d0, d1, ..., dn)
        Random values.

In [37]:
import numpy as np
u = np.random.rand(3, 3)
u

array([[0.95190017, 0.33837644, 0.8006769 ],
       [0.45454356, 0.53758736, 0.82399991],
       [0.36842148, 0.51523525, 0.27571348]])

### Function 2: <font color = 'blue'><code>numpy.random.randn()</code></font>

<code>numpy.random.randn(d0, d1, ..., dn)</code>

 - Return a sample (or samples) from the “standard normal” distribution.

 - If positive, int_like or int-convertible arguments are provided, randn generates an array of shape <code>(d0, d1, ..., dn)</code>, filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation). A single float randomly sampled from the distribution is returned if no argument is provided.
 
 - This is a convenience function. If you want an interface that takes a tuple as the first argument, use [numpy.random.standard_normal](https://numpy.org/doc/1.16/reference/generated/numpy.random.standard_normal.html#numpy.random.standard_normal) instead.

 - <b>Parameters:</b>	
        d0, d1, …, dn : int, optional
        The dimensions of the returned array, should be all positive. If no argument is given a single Python float is returned.

 - <b>Returns:</b>	
        Z : ndarray or float
        A (d0, d1, ..., dn)-shaped array of floating-point samples from the standard normal distribution, or a single such float if no parameters were supplied.

In [38]:
a = np.random.randn(5)
a

array([-2.38409378,  0.69977806, -0.86288579,  0.65072579, -1.08427449])

In [39]:
b = np.random.randn(3, 3)
b

array([[ 0.16936334, -0.60779225,  0.33680942],
       [ 0.86042356, -0.03838367, -0.85896827],
       [-0.25929984, -1.05606481, -2.21401676]])

### Function 3: <font color = 'blue'><code>numpy.random.randint()</code></font>

<code>numpy.random.randint(low, high=None, size=None, dtype='l')</code>

 - Return random integers from low (inclusive) to high (exclusive).

 - Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).
 
 - <b>Parameters:</b>	
     - <b>low</b> : <code>int</code>
            Lowest (signed) integer to be drawn from the distribution (unless high=None, in which case this parameter is one above the highest such integer).

     - <b>high</b> : <code>int, optional</code>
            If provided, one above the largest (signed) integer to be drawn from the distribution (see above for behavior if high=None).

     - <b>size</b> : <code>int or tuple of ints, optional</code>
            Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

     - <b>dtype</b> : <code>dtype, optional</code>
            Desired dtype of the result. All dtypes are determined by their name, i.e., ‘int64’, ‘int’, etc, so byteorder is not available and a specific precision may have different C types depending on the platform. The default value is ‘np.int’. returned.

 - <b>Returns:</b>	
    - <b>out</b> : <code>int or ndarray of ints</code>
            size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.

In [40]:
np.random.randint(5,20)       # Returns one rand integer between the values 5 & 19(20 is excluded)

16

In [41]:
np.random.randint(20,50,5)  # Returns  5 rand integers between 20 & 49(50 is excluded)

array([30, 23, 38, 43, 24])

# <font color = 'green'>Part III: Array Indexing and Slicing</font>

Elements and subarrays of NumPy arrays are accessed using the standard square bracket notation that is also used with Python lists. Within the square bracket, a variety of different index formats are used for different types of element selection. In general, the expression within the bracket is a tuple, where each item in the tuple is a specification of which elements to select from each axis (dimension) of the array.

Slices are specified using the <code>:</code> notation that is also used for Python lists. In this notation, a range of elements can be selected using an expression like <code>m:n</code>, which selects elements starting with m and ending with n − 1 (note that the nth element is not included). The slice <code>m:n</code> can also be written more explicitly as <code>m : n : 1</code>, where the number 1 specifies that every element between m and n should be selected. To select every second element between m and n, use <code>m : n : 2</code>, and to select every p elements, use <code>m : n : p</code>, and so on. If p is negative, elements are returned in reversed order starting from m to n+1 (which implies that m has to be larger than n in this case). See Table 2-4 for a summary of indexing and slicing operations for NumPy arrays.


<img src="assets/5_numpy_slicing.jpg" width=600px />

### <font color = 'green'>3.1 Array Slicing: 1D Arrays</font>

The following examples demonstrate index and slicing operations for NumPy arrays. To begin with, consider an array with a single axis (dimension) that contains a sequence of integers between 0 and 10:

In [42]:
a = np.arange(0, 11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
# a[m : n : p]: m = start index, n = stop index, p = increment. 

a = np.arange(0, 11)
print(f'a: {a}')
print(f'a[0] = {a[0]}')
print(f'a[-1] = {a[-1]}')
print(f'a[4] = {a[4]}')

#To select a range of element, say from the second to the second-to-last element, selecting every element and every second element, respectively, we can use index slices:

print(f'a[1:-1] = {a[1:-1]}')
print(f'a[1:-1:2] = {a[1:-1:2]}')

# To select the first five and the last five elements from an array, we can use the slices :5 and –5:, since if m or n is omitted in m:n, the defaults are the beginning and the end of the array, respectively.

print(f'a[:5] = {a[:5]}')
print(f'a[-5:] = {a[-5:]}')

# To reverse the array and select only every second value, we can use the slice ::-2, as shown in the following example:

print(f'a[::-1] = {a[::-1]}')
print(f'a[::-2] = {a[::-2]}')

a: [ 0  1  2  3  4  5  6  7  8  9 10]
a[0] = 0
a[-1] = 10
a[4] = 4
a[1:-1] = [1 2 3 4 5 6 7 8 9]
a[1:-1:2] = [1 3 5 7 9]
a[:5] = [0 1 2 3 4]
a[-5:] = [ 6  7  8  9 10]
a[::-1] = [10  9  8  7  6  5  4  3  2  1  0]
a[::-2] = [10  8  6  4  2  0]


### <font color = 'green'>3.2 Array Slicing: ND Arrays</font>

With multidimensional arrays, element selections like those introduced in the previous section can be applied on each axis (dimension). The result is a <b>reduced array</b> where each element matches the given selection rules. 

The general formats used are 

<code>sample_matrix[row][col]</code> 

    or

<code>sample_matrix[row,col]</code>

We will use the second option as standard.

As a specific example, consider the following 2D array:

In [44]:
f = lambda m, n: n + 10 * m
A = np.fromfunction(f, (6, 6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [45]:
g = lambda m, n: m*m
B = np.fromfunction(g, (3, 3), dtype=int)
B

array([[0, 0, 0],
       [1, 1, 1],
       [4, 4, 4]])

In [46]:
f = lambda m, n: n + 10 * m
A = np.fromfunction(f, (6, 6), dtype=int)

print(A)
print()

# Extracting the i-th row:
for i in range(6):
    print(f'Row {i}: {A[i, :]}')
    
print()
    
# Extracting the j-th column:
for j in range(6):
    print(f'Column {j}: {A[:, j]}')

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]

Row 0: [0 1 2 3 4 5]
Row 1: [10 11 12 13 14 15]
Row 2: [20 21 22 23 24 25]
Row 3: [30 31 32 33 34 35]
Row 4: [40 41 42 43 44 45]
Row 5: [50 51 52 53 54 55]

Column 0: [ 0 10 20 30 40 50]
Column 1: [ 1 11 21 31 41 51]
Column 2: [ 2 12 22 32 42 52]
Column 3: [ 3 13 23 33 43 53]
Column 4: [ 4 14 24 34 44 54]
Column 5: [ 5 15 25 35 45 55]


In [47]:
#Extracting the (i, j) th element:
print(f'A[2, 3]: {A[2,3]}')
print(f'A[4, 4]: {A[4,4]}')  # using A[i, j]
print(f'A[5, 5]: {A[5][5]}') # using A[i][j]

A[2, 3]: 23
A[4, 4]: 44
A[5, 5]: 55


In [48]:
print(A)
print(A[:4, :4])
print(A[1:5, 1:5])

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [49]:
print(A)
A[:4, 2:]

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


array([[ 2,  3,  4,  5],
       [12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35]])

In [50]:
print(A)
A[2:, 2:]

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


array([[22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45],
       [52, 53, 54, 55]])

In [51]:
# With element spacing other that 1, submatrices made up from nonconsecutive elements can be extracted:
A[::2, ::2] # every second element starting from 0, 0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [52]:
A[1::2, 1::3] # every second and third element starting from 1, 1

array([[11, 14],
       [31, 34],
       [51, 54]])

### <font color = 'green'>3.3 Array Slicing: ND Array Views</font>

Subarrays that are extracted from arrays using slice operations are <font color = 'grey'>**alternative views of the same underlying array data**</font>. That is, they are arrays that refer to the same data in the memory as the original array, but with a different <code>strides</code> configuration. When elements in a view are assigned new values, the values of the original array are therefore also updated. For example,

In [53]:
B = A[1:5, 1:5]
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [54]:
B[:, :] = 0
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

Here, assigning new values to the elements in an array B, which is created from the array A, also modifies the values in A (since both arrays refer to the same data in the memory). The fact that extracting subarrays results in views rather than new
independent arrays eliminates the need for copying data and improves performance. When a copy rather than a view is needed, the view can be copied explicitly by using the <code>copy</code> method of the <code>ndarray</code> instance.

### <font color = 'blue'><code>ndarray.copy():</code></font>

In [55]:
C = B[1:3, 1:3].copy()
C

array([[0, 0],
       [0, 0]])

In [56]:
C[:, :] = 1 # this does not affect B since C is a copy of the view B[1:3, 1:3]

# In addition to the copy attribute of the ndarray class, an array can also be copied using the function np.copy or, equivalently, using the np.array function with the keyword argument copy=True.

print(C)
print(A)

[[1 1]
 [1 1]]
[[ 0  1  2  3  4  5]
 [10  0  0  0  0 15]
 [20  0  0  0  0 25]
 [30  0  0  0  0 35]
 [40  0  0  0  0 45]
 [50 51 52 53 54 55]]


In [57]:
D = B[1:3, 1:3]
D[:, :] = 1
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  1,  1,  0, 25],
       [30,  0,  1,  1,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

### <font color = 'green'>3.4 Array Indexing: Fancy Indexing and Boolean valued Indexing</font>

#### Fancy Indexing:

In the previous section, we looked at indexing NumPy arrays with integers and slices, to
extract individual elements or ranges of elements. NumPy provides another convenient
method to index arrays, called fancy indexing. With fancy indexing, an array can be
indexed with another NumPy array, a Python list, or a sequence of integers, whose
values select elements in the indexed array. To clarify this concept, consider the
following example: we first create a NumPy array with 11 floating-point numbers, and
then index the array with another NumPy array (and Python list and a tuple), to extract element
numbers 0, 2, and 4 from the original array:

In [58]:
A = np.linspace(0, 1, 11)
print(A)
print(A[np.array((1, 3, 5))])

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[0.1 0.3 0.5]


In [59]:
A[np.array([0, 2, 4, 6])] # Using an array for index

array([0. , 0.2, 0.4, 0.6])

In [60]:
A[[1, 3, 5]] # Using a list for index

array([0.1, 0.3, 0.5])

In [61]:
import numpy as np
A = np.random.randint(1, 50, 16).reshape(4,4)
print(A)
print()

print(f'A - Dimention: {A.ndim}')
print(f'A - shape: {A.shape}')

# ith row:
print(f'Second row: \n {A[1, :]}')
print(f'First and third rows: \n {A[(0, 2), :]}')
print(f'First three rows: \n {A[:3, :]}')
print()

# jth column:
print(f'Second Column: \n {A[:, 1].reshape(4, 1)}')
print(f'First and third Columns: \n {A[:, (0, 2)].reshape(4, 2)}')
print(f'First three Columns: \n {A[:, :3].reshape(4, 3)}')

[[ 6 48 45 12]
 [32 11 15 14]
 [39 38 47 46]
 [12 22 27  2]]

A - Dimention: 2
A - shape: (4, 4)
Second row: 
 [32 11 15 14]
First and third rows: 
 [[ 6 48 45 12]
 [39 38 47 46]]
First three rows: 
 [[ 6 48 45 12]
 [32 11 15 14]
 [39 38 47 46]]

Second Column: 
 [[48]
 [11]
 [38]
 [22]]
First and third Columns: 
 [[ 6 45]
 [32 15]
 [39 47]
 [12 27]]
First three Columns: 
 [[ 6 48 45]
 [32 11 15]
 [39 38 47]
 [12 22 27]]


#### Boolean Valued Indexing:

Another variant of indexing NumPy arrays is to use Boolean-valued index arrays. In
this case, each element (with values True or False) indicates whether or not to select the
element from the list with the corresponding index. That is, if element n in the indexing
array of Boolean values is True, then element n is selected from the indexed array. If the
value is False, then element n is not selected. This index method is handy when filtering out
elements from an array. For example, to select all the elements from the array A (as defined in
the preceding section) that exceed the value 0.5, we can use the following combination of the
comparison operator applied to a NumPy array and indexing using a Boolean-valued array:

In [62]:
A[A > 0.5]

array([ 6, 48, 45, 12, 32, 11, 15, 14, 39, 38, 47, 46, 12, 22, 27,  2])

Unlike arrays created by using slices, the arrays returned using fancy indexing and
Boolean-valued indexing are not views but rather new independent arrays. Nonetheless,
it is possible to assign values to elements selected using fancy indexing:

In [63]:
A = np.arange(0, 11, 1)
indices = [2, 4, 6]
B = A[indices]
B[0] = -1 # This does not affect A, because B = A[indices] is not a 'view' of A but an independent array.
print(f'B : {B}')
A[indices] = -1
print(f'A : {A}')

B : [-1  4  6]
A : [ 0  1 -1  3 -1  5 -1  7  8  9 10]


In [64]:
# And likewise for boolean valued indexing:

A = np.arange(0, 11, 1)
B = A[A > 5]
B[0] = -1 # This does not affect A, because B = A[A > 5] is not a 'view' of A but an independent array.
A[A >5] = -1
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1, -1])

# <font color = 'green'>Part IV: Array Reshaping and Resizing</font>

When working with data in array form, it is often useful to rearrange arrays and alter the
way they are interpreted. For example, an $N × N$ matrix array could be rearranged into a
vector of length $N^2$, or a set of one-dimensional arrays could be concatenated together
or stacked next to each other to form a matrix. NumPy provides a rich set of functions of
this type of manipulation. See Table 2-5 for a summary of a selection of these functions.

<img src="assets/6_numpy_reshape.jpg" width=650px />

### <font color = 'blue'>4.1. Function 1: <code>reshape()</code></font>

Reshaping an array does not require modifying the underlying array data; it only
changes in how the data is interpreted, by redefining the array’s strides attribute.
An example of this type of operation is a 2 × 2 array (matrix) that is reinterpreted as a 4 x 1 array or a 
1 × 4 array (vector). In NumPy, the function <code>np.reshape</code>, or the <code>ndarray</code> class method
<code>reshape</code>, can be used to reconfigure how the underlying data is interpreted. It takes an
array and the new shape of the array as arguments:

In [65]:
a = np.array([[1, 2], [3, 4]])
b = np.reshape(a, (1, 4)) # using np.reshape() function
c = np.reshape(a, (4, 1))
d = c.reshape(2, 2) # using the ndarray method reshape() for the class instance 'c'. 
print(f'a: {a}')
print(f'b: {b}')
print(f'c: {c}')
print(f'd: {d}')

a: [[1 2]
 [3 4]]
b: [[1 2 3 4]]
c: [[1]
 [2]
 [3]
 [4]]
d: [[1 2]
 [3 4]]


 - It is necessary that the requested new shape of the array match the number of elements in the original size. However, the number of axes (dimensions) does not need to be conserved, as illustrated in the previous example, where in the first case, the new array has dimension 2 and shape (1, 4), while in the second case, the new array has dimension 1 and shape (4,). 

 - This example also demonstrates two different ways of invoking the reshape operation: using the function <code>np.reshape</code> and the <code>ndarray</code> method <code>reshape</code>. Note that <font color = 'blue'>**reshaping an array produces a view of the array**</font>, and if an independent copy of the array is needed, the view has to be copied explicitly (e.g., using <code>np.copy()</code>).

### <font color = 'blue'>4.2. Function 2: <code>np.ravel()</code> and <code>np.flatten()</code></font>

The <code>np.ravel</code> (and its corresponding ndarray method) is a special case of <code>reshape</code>,
which collapses all dimensions of an array and returns a flattened one-dimensional
array with a length that corresponds to the total number of elements in the original
array. The <code>ndarray</code> method <code>flatten</code> performs the same function but returns a copy
instead of a view.

In [66]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [67]:
data.flatten()

array([1, 2, 3, 4])

In [68]:
data.flatten().shape

(4,)

### <font color = 'blue'>4.3. Function 3: <code>np.newaxis()</code> and <code>np.expand_dims()</code></font>

While <code>np.ravel</code> and <code>np.flatten</code> collapse the axes of an array into a one-dimensional
array, it is also possible to introduce new axes into an array, either by using <code>np.reshape</code>
or, when adding new empty axes, using indexing notation and the <code>**np.newaxis**</code> keyword
at the place of a new axis. In the following example, the array data has one axis, so it
should normally be indexed with a tuple with one element. However, if it is indexed with
a tuple with more than one element, and if the extra indices in the tuple have the value
<code>**np.newaxis()**</code>, then the corresponding new axes are added:

In [69]:
data = np.arange(0, 5)
column = data[:, np.newaxis]
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [70]:
row = data[np.newaxis, :]
row

array([[0, 1, 2, 3, 4]])

The function <code>np.expand_dims()</code> can also be used to add new dimensions to an
array, and in the preceding example, the expression <code>data[:, np.newaxis]</code> is
equivalent to <code>np.expand_dims(data, axis=1)</code>, and <code>data[np.newaxis, :]</code> is equivalent
to <code>np.expand_dims(data, axis=0)</code>. Here the axis argument specifies the location
relative to the existing axes where the new axis is to be inserted.

In [71]:
a = np.random.randint(0, 50, 27).reshape(3, 3, 3)
b = a.flatten()
print(a)
print(b)
print(f'a - Dimention: {a.ndim}')
print(f'a - Shape    : {a.shape}')
print(f'b - Dimention: {b.ndim}')
print(f'b - Shape    : {b.shape}')
c = np.expand_dims(b, axis=0)
print(c)
print(f'c - Dimention: {c.ndim}')
print(f'c - Shape    : {c.shape}')

[[[47 34 40]
  [35 23 37]
  [12  2 49]]

 [[27 20 13]
  [ 0 10  0]
  [18 31 11]]

 [[27 31 28]
  [19 41 35]
  [19 21 15]]]
[47 34 40 35 23 37 12  2 49 27 20 13  0 10  0 18 31 11 27 31 28 19 41 35
 19 21 15]
a - Dimention: 3
a - Shape    : (3, 3, 3)
b - Dimention: 1
b - Shape    : (27,)
[[47 34 40 35 23 37 12  2 49 27 20 13  0 10  0 18 31 11 27 31 28 19 41 35
  19 21 15]]
c - Dimention: 2
c - Shape    : (1, 27)


### <font color = 'blue'>4.4. Function 4: Merging arrays into bigger arrays; vertically or horizontally: <code>np.vstack()</code>, <code>np.hstack()</code> and <code>np.concatenate()</code></font>

#### 4.4.1 <code>np.vstack():</code>

We have up to now looked at methods to rearrange arrays in ways that do not affect
the underlying data. Earlier in this chapter, we also looked at how to extract subarrays
using various indexing techniques. In addition to reshaping and selecting subarrays,
it is often necessary to merge arrays into bigger arrays, for example, when joining
separately computed or measured data series into a higher-dimensional array, such as
a matrix. For this task, NumPy provides the functions <code>np.vstack</code>, for vertical stacking of,
for example, rows into a matrix, and <code>np.hstack</code> for horizontal stacking of, for example,
columns into a matrix. The function <code>np.concatenate</code> provides similar functionality, but
it takes a keyword argument axis that specifies the axis along which the arrays are to be
concatenated.
The shape of the arrays passed to <code>np.hstack</code>, <code>np.vstack</code>, and <code>np.concatenate</code>
is important to achieve the desired type of array joining. For example, consider the
following cases: say we have one-dimensional arrays of data, and we want to stack them
vertically to obtain a matrix where the rows are made up of the one-dimensional arrays.
We can use np.vstack to achieve this:

In [72]:
a = np.array([x for x in range(1, 5)], dtype=np.int)
b = np.array([x for x in range(5, 9)], dtype=np.int)
c = np.array([x for x in range(9, 13)], dtype=np.int)
print(f'a: {a}; b: {b}; c: {c}')

A = np.vstack((a, b, c))  # Stacking the arrays a, b, c vertically
B = np.hstack((a, b, c))  # Stacking the arrays a, b, c horizontally

print(f'A: a + b + c vertically:\n {A}')
print(f'B: a + b + c horizontally:\n {B}')

# If we instead want to stack the arrays horizontally, to obtain a matrix where the arrays are the column vectors,then we need to make np.hstack() treat the input arrays as columns and stack them accordingly.

# we need to make the input arrays two-dimensional arrays of shape (1, 5) rather than one-dimensional arrays of shape (5,). As discussed earlier, we can insert a new axis by indexing with np.newaxis:



a: [1 2 3 4]; b: [5 6 7 8]; c: [ 9 10 11 12]
A: a + b + c vertically:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
B: a + b + c horizontally:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


#### 4.4.2 <code>np.hstack():</code>

In [73]:
a = np.array([x for x in range(1, 5)], dtype=np.int)
b = np.array([x for x in range(5, 9)], dtype=np.int)
c = np.array([x for x in range(9, 13)], dtype=np.int)

a = np.expand_dims(a, axis = 1)
b = np.expand_dims(b, axis = 1)
c = np.expand_dims(c, axis = 1)

C = np.hstack((a, b, c))
print(f'C: a + b + c horizontally as columns:\n {C}')

C: a + b + c horizontally as columns:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


#### 4.4.3 <code>np.concatinate():</code>

In [74]:
import numpy as np 
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.concatenate((a,b))
d = np.concatenate((a,b),axis = 1)

print('First array:') 
print(a)
print()  

print('Second array:') 
print(b) 
print()  
# both the arrays are of same dimensions 

print('c = a + b along axis 0:')
print(c) 
print(f'c - Dimention: {c.ndim}')
print()

print('d = a + b along axis 1:') 
print(d)
print(f'd - Dimention: {d.ndim}') 

First array:
[[1 2]
 [3 4]]

Second array:
[[5 6]
 [7 8]]

c = a + b along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
c - Dimention: 2

d = a + b along axis 1:
[[1 2 5 6]
 [3 4 7 8]]
d - Dimention: 2


# <font color = 'green'>Part V: Vectorization and Array Broadcasting</font>

## <font color = 'blue'>5.1 Vectorization and Array Broadcasting</font>

The purpose of storing numerical data in arrays is to be able to process the data with
concise vectorized expressions that represent batch operations that are applied to all
elements in the arrays. Efficient use of vectorized expressions eliminates the need of
many explicit for loops. This results in less verbose code, better maintainability, and
higher-performing code. NumPy implements functions and vectorized operations
corresponding to most fundamental mathematical functions and operators. Many
of these functions and operations act on arrays on an elementwise basis, and binary
operations require all arrays in an expression to be of compatible size. The meaning of compatible size is normally that the variables in an expression represent either scalars
or arrays of the same size and shape. More generally, a binary operation involving two
arrays is well defined if the arrays can be broadcasted into the same shape and size.

In the case of an operation between a scalar and an array, broadcasting refers to the
scalar being distributed and the operation applied to each element in the array. When
an expression contains arrays of unequal sizes, the operations may still be well defined if
the smaller of the array can be broadcasted (“effectively expanded”) to match the larger
array according to NumPy’s broadcasting rule: <font color = 'blue'>*an array can be broadcasted over another
array if their axes on a one-by-one basis either have the same length or if either of them
have length 1. If the number of axes of the two arrays is not equal, the array with fewer
axes is padded with new axes of length 1 from the left until the numbers of dimensions of
the two arrays agree.*</font>

Two simple examples that illustrate array broadcasting are shown in Figure 2-2: a
3 × 3 matrix is added to a 1 × 3 row vector and a 3 × 1 column vector, respectively, and
in both cases the result is a 3 × 3 matrix. However, the elements in the two resulting
matrices are different, because the way the elements of the row and column vectors are
broadcasted to the shape of the larger array is different depending on the shape of the
arrays, according to NumPy’s broadcasting rule.

<img src="assets/7_np_array_broadcasting.jpg" width=600px />

## <font color = 'blue'>5.2 Arithmatic Operations</font>

In [75]:
A = np.array([[5, 6], [7, 8]])
B = np.array([[1, 2], [3, 4]])
print(f'A + B: \n{A+B}')
print()
print(f'A - B: \n{A-B}')
print()
print(f'A * B: \n{A*B}')
print()
print(f'A / B: \n{A/B}')
print()
print(f'A ** B: \n{A**B}')
print()
print(f'A ^ B: \n{A^B}') # Bitwise operators work on element basis as well.

A + B: 
[[ 6  8]
 [10 12]]

A - B: 
[[4 4]
 [4 4]]

A * B: 
[[ 5 12]
 [21 32]]

A / B: 
[[5.         3.        ]
 [2.33333333 2.        ]]

A ** B: 
[[   5   36]
 [ 343 4096]]

A ^ B: 
[[ 4  4]
 [ 4 12]]


In [76]:
x = np.random.randint(1, 30, 16).reshape(4, 4)
print(x)
print()
y = np.array([1, 1, 2, 2])
a = np.expand_dims(y, axis = 0) # Broadcasted horizontally
b = np.expand_dims(y, axis = 1) # Broadcasted vertically
print(x/a)
print()
print(x/b)
print()

[[26 27 12 25]
 [16 19 20  7]
 [22 23 16  6]
 [20  1  4  9]]

[[26.  27.   6.  12.5]
 [16.  19.  10.   3.5]
 [22.  23.   8.   3. ]
 [20.   1.   2.   4.5]]

[[26.  27.  12.  25. ]
 [16.  19.  20.   7. ]
 [11.  11.5  8.   3. ]
 [10.   0.5  2.   4.5]]



## <font color = 'blue'>5.3 Universal Array Functions</font>

In addition to arithmetic expressions using operators, NumPy provides vectorized
functions for elementwise evaluation of many elementary mathematical functions
and operations.

<img src="assets/8_np_operators.jpg" width=360px />

<img src="assets/9_np_functions.jpg" width=520px />

<img src="assets/10_np_functions.jpg" width=520px />

In [77]:
a = np.random.randint(1, 50, 16).reshape(4, 4)
np.sqrt(a)

array([[5.74456265, 3.16227766, 5.91607978, 6.08276253],
       [4.47213595, 6.92820323, 6.08276253, 3.16227766],
       [4.69041576, 5.91607978, 6.40312424, 3.60555128],
       [5.19615242, 6.63324958, 5.83095189, 4.        ]])

In [78]:
np.exp(a)

array([[2.14643580e+14, 2.20264658e+04, 1.58601345e+15, 1.17191424e+16],
       [4.85165195e+08, 7.01673591e+20, 1.17191424e+16, 2.20264658e+04],
       [3.58491285e+09, 1.58601345e+15, 6.39843494e+17, 4.42413392e+05],
       [5.32048241e+11, 1.28516001e+19, 5.83461743e+14, 8.88611052e+06]])

In [79]:
np.max(a)

48

In [80]:
np.argmax(a)

5

In [81]:
np.min(a)

10

In [82]:
np.argmin(a)

1

In [83]:
np.sin(a)

array([[ 0.99991186, -0.54402111, -0.42818267, -0.64353813],
       [ 0.91294525, -0.76825466, -0.64353813, -0.54402111],
       [-0.00885131, -0.42818267, -0.15862267,  0.42016704],
       [ 0.95637593,  0.01770193,  0.52908269, -0.28790332]])

In [84]:
np.log(a)

array([[3.49650756, 2.30258509, 3.55534806, 3.61091791],
       [2.99573227, 3.87120101, 3.61091791, 2.30258509],
       [3.09104245, 3.55534806, 3.71357207, 2.56494936],
       [3.29583687, 3.78418963, 3.52636052, 2.77258872]])

In [85]:
np.cos(a)

array([[-0.01327675, -0.83907153, -0.90369221,  0.76541405],
       [ 0.40808206, -0.64014434,  0.76541405, -0.83907153],
       [-0.99996083, -0.90369221, -0.98733928,  0.90744678],
       [-0.29213881,  0.99984331, -0.84857027, -0.95765948]])

In [86]:
np.square(a)

array([[1089,  100, 1225, 1369],
       [ 400, 2304, 1369,  100],
       [ 484, 1225, 1681,  169],
       [ 729, 1936, 1156,  256]], dtype=int32)

In [87]:
b = np.cos(a)

In [88]:
np.round(b)

array([[-0., -1., -1.,  1.],
       [ 0., -1.,  1., -1.],
       [-1., -1., -1.,  1.],
       [-0.,  1., -1., -1.]])

In [89]:
np.round(b, decimals = 2)

array([[-0.01, -0.84, -0.9 ,  0.77],
       [ 0.41, -0.64,  0.77, -0.84],
       [-1.  , -0.9 , -0.99,  0.91],
       [-0.29,  1.  , -0.85, -0.96]])

In [90]:
np.std(b)

0.754647569174372

In [91]:
np.mean(b)

-0.2736510604366563

In [92]:
a = np.array([1, 2, 3, 4, 5])
b = [1, 3, 5]
np.in1d(b, a)

array([ True,  True,  True])

# <font color = 'green'>Part VI: Input and Output</font>

In [93]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
# Saving and loading arrays in numpy files.

np.save('myarray', a)

In [95]:
a = np.arange(11)
b = np.random.randint(1, 20, 10)
np.savez('myarrays.npz', c = a, d = b)

In [96]:
archived_arrays = np.load('myarrays.npz')
archived_arrays['d']

array([12, 18, 12,  1, 10, 14,  3,  1, 12, 17])

In [97]:
# Saving and loading arrays to a text file.

a = np.random.randint(1, 40, 16).reshape(4, 4)
np.savetxt('myarray.txt', a, delimiter = ',')

In [98]:
b = np.loadtxt('myarray.txt', delimiter = ',')
b

array([[ 8., 17., 29., 35.],
       [ 8., 12.,  3., 29.],
       [ 3., 16.,  2., 34.],
       [13., 39.,  9., 30.]])